name: HarmonyOS Build Check

on:
  pull_request:
    branches:
      - dev

  push:
    branches:
      - dev


jobs:
  build:

    name: Build HarmonyOS Project

    runs-on: ubuntu-latest

    steps:

      # 拉取代码
      - name: Checkout repository
        uses: actions/checkout@v4


      # HarmonyOS Hvigor 需要 JDK
      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17


      # Hvigor依赖Node环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm


      # 安装npm依赖
      - name: Install dependencies
        run: npm install


      # 执行HarmonyOS构建
      - name: Build HAP
        run: |
          chmod +x hvigorw
          hvigor assembleHap
